<?xml version="1.0"?>
<package format="3">
  <name>romer_node_utils</name>
  <version>0.0.0</version>
  <description>This package contains parent class for most generic ros node structure and helper methods for reading parameters from rosparam</description>

  <maintainer email="m.efetiryaki@gmail.com">Mehmet Efe Tiryaki</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>rosgraph_msgs</depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
